import { connectDB } from "../lib/mongo";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = await connectDB();

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
